---
format: html
editor: visual
---

# Program {.unnumbered}

*for a more detailed program see the* [More Info](useful.qmd) *section*

+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | SESSION | Time        | **Topic**                                                                                             | Presenters                                                  |
+=============================+:=======:+:===========:+:=====================================================================================================:+:===========================================================:+
| EPISODE I                   | W1      | 9am -11am   | **Harnessing genomic resources for conservation of biodiversity**                                     | Laura Bertola & Kate Rick                                   |
|                             |         |             |                                                                                                       |                                                             |
| THE DIVERSITY AWAKENS       |         |             |                                                                                                       |                                                             |
|                             |         |             |                                                                                                       |                                                             |
| Monday                      |         |             |                                                                                                       |                                                             |
|                             |         |             |                                                                                                       |                                                             |
| 09/03/26                    |         |             |                                                                                                       |                                                             |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W2      | 11:30am-1pm | **dartR Intro, Data Manipulation & Filtering**                                                        | Arthur Georges & Ching Ching Lau                            |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W3      | 2pm-3:30pm  | **Sex-Linked Markers**                                                                                | Diana Robledo & Floriaan Devloo-Delva                       |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| EPISODE II                  | W4      | 9am -11am   | **Subdivisions, biological and administrative: their importance for management**                      | Bill Sherwin, Floriaan Devloo-Delva and Laura Bertola       |
|                             |         |             |                                                                                                       |                                                             |
| THE BOTTLENECK STRIKES BACK |         |             |                                                                                                       |                                                             |
|                             |         |             |                                                                                                       |                                                             |
| Tuesday                     |         |             |                                                                                                       |                                                             |
|                             |         |             |                                                                                                       |                                                             |
| 10/03/26                    |         |             |                                                                                                       |                                                             |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W5      | 11:30am-1pm | **These are not the SNP you're looking for: how study design impacts population genetic assessments** | Renee Catullo                                               |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W6      | 2pm-3:30pm  | **Management of Small Populations**                                                                   | Diana Robledo                                               |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| EPISODE III                 | W7      | 9am -11am   | **Effective Population Size & Historical** $N_e$                                                      | Robin Waples, Luis Mijangos & Bernd Gruber                  |
|                             |         |             |                                                                                                       |                                                             |
| THE ATTACK OF THE CLADES    |         |             |                                                                                                       |                                                             |
|                             |         |             |                                                                                                       |                                                             |
| Wednesday                   |         |             |                                                                                                       |                                                             |
|                             |         |             |                                                                                                       |                                                             |
| 11/03/26                    |         |             |                                                                                                       |                                                             |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W8      | 11:30am-1pm | **Genetic Divergence & Phylogenetics**                                                                | Craig Moritz & Arthur Georges                               |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W9      | 2pm-3:30pm  | **dartR developer/new & hidden features/manipulate plots/eBooks**                                     | Bernd Gruber, Arthur Georges, Luis Mijangos & Ethan Halford |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| EPISODE IV                  | W10     | 9am -11am   | **Natural Selection and Adaption**                                                                    | Luciano Beheregaray & Chris Brauer                          |
|                             |         |             |                                                                                                       |                                                             |
| A NEW FLOW                  |         |             |                                                                                                       |                                                             |
|                             |         |             |                                                                                                       |                                                             |
| Thursday                    |         |             |                                                                                                       |                                                             |
|                             |         |             |                                                                                                       |                                                             |
| 12/03/26                    |         |             |                                                                                                       |                                                             |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W11     | 11:30am-1pm | **Landscape Genetics**                                                                                | Robyn Shaw, Cynthia Riginos & Zoe Meziere                   |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W12     | 2pm-3:30pm  | **AI in PopGen & Research**                                                                           | Jonathan Ting, Darya Vanichkina & Celine Frere              |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| EPISODE V                   | W13     | 9am -11am   | **Computer Simulations**                                                                              | Bernd Gruber & Luis Mijangos                                |
|                             |         |             |                                                                                                       |                                                             |
| THE RETURN OF THE SCIENTIST |         |             |                                                                                                       |                                                             |
|                             |         |             |                                                                                                       |                                                             |
| Friday                      |         |             |                                                                                                       |                                                             |
|                             |         |             |                                                                                                       |                                                             |
| 13/03/26                    |         |             |                                                                                                       |                                                             |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W14     | 11:30am-1pm | **SNPs that Matter**                                                                                  | Elise Furlan                                                |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W15     | 2pm-3:30pm  | **Relatedness**                                                                                       | Ethan Halford & Luis Mijangos                               |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|                             | W16     | 9am -11am   | **Sequencing Technologies**                                                                           | Andrzej Kilian                                              |
+-----------------------------+---------+-------------+-------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+

: {tbl-colwidths="\[5,5,20, 30, 40\]" .striped .bordered}
